server:
  port: 8900

spring:
  application:
    name: dubbo-user-service  
     
user:
  service:
    version: 1.0.0 
      
dubbo:
  scan:
    base-packages: com.dubbo.demo.service
  application:
    id:  dubbo-user-service 
    name: dubbo-user-service 
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://192.168.168.131:2181?backup=192.168.168.128:2181,192.168.168.130:2181
    
    
    
    
